version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: modelproject2-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: modelproject
      MYSQL_USER: user
      MYSQL_PASSWORD: my-secret-pw
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    image: model-project1
    container_name: modelproject2-app
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/modelproject
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: my-secret-pw
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
volumes:
  mysql_data:
